#!/usr/bin/env python3
"""
Contrastive SSL Pretraining with Synthetic Waymo Episodes.

This script extends train_contrastive_ssl.py to work with the synthetic
images generated by generate_synthetic_images.py.

The pipeline:
1. Load frames from synthetic Waymo episodes (JSON + images)
2. Extract embeddings via TinyMultiCamEncoder
3. Compute SimCLR-style contrastive loss (treating cameras as augmentations)
4. Save checkpoints for downstream waypoint BC use

Usage:
    python train_contrastive_ssl_synthetic.py --episodes-dir data/waymo/episodes \
        --images-dir data/waymo/images --batch-size 8 --num-steps 100
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from PIL import Image


def _require_torch():
    try:
        import torch
    except Exception as e:
        raise RuntimeError("This script requires PyTorch.") from e
    return torch


@dataclass
class Config:
    # Data
    episodes_dir: str = "data/waymo/episodes"
    images_dir: str = "data/waymo/images"
    batch_size: int = 8
    num_steps: int = 100
    max_cameras: int = 4
    
    # Model
    encoder_out_dim: int = 128
    encoder_hidden_dim: int = 128
    
    # Training
    lr: float = 1e-3
    temperature: float = 0.1
    
    # Output
    out_dir: str = "out/pretrain_contrastive_synthetic"
    checkpoint_every: int = 20
    log_every: int = 5
    image_size: int = 224


class SyntheticEpisodesDataset:
    """Dataset for synthetic Waymo episodes with local images."""
    
    def __init__(
        self,
        episodes_dir: str,
        images_dir: str,
        camera_names: List[str] = None,
        image_size: int = 224,
    ):
        self._torch = _require_torch()
        self.episodes_dir = Path(episodes_dir)
        self.images_dir = Path(images_dir)
        self.camera_names = camera_names or ["front", "left", "right", "rear"]
        self.image_size = image_size
        
        self.episode_files = sorted(self.episodes_dir.glob("syn_*.json"))
        
        if not self.episode_files:
            raise ValueError(f"No episode files found in {episodes_dir}")
        
        self.index: List[tuple] = []
        
        for ep_path in self.episode_files:
            with open(ep_path, "r") as f:
                ep_data = json.load(f)
            
            episode_id = ep_data.get("episode_id", ep_path.stem)
            num_frames = len(ep_data.get("frames", []))
            
            for frame_idx in range(num_frames):
                img_dir = self.images_dir / f"episode_{episode_id}" / f"frame_{frame_idx:04d}"
                
                image_paths = {}
                for cam in self.camera_names:
                    img_path = img_dir / f"{cam}.png"
                    if img_path.exists():
                        image_paths[cam] = img_path
                    else:
                        image_paths[cam] = None
                
                self.index.append((episode_id, frame_idx, image_paths))
        
        print(f"[SyntheticEpisodesDataset] Loaded {len(self.episode_files)} episodes, "
              f"{len(self.index)} frames")
    
    def __len__(self) -> int:
        return len(self.index)
    
    def __getitem__(self, idx: int) -> Dict:
        torch = self._torch
        episode_id, frame_idx, image_paths = self.index[idx]
        
        images_by_cam = {}
        valid_by_cam = {}
        
        for cam in self.camera_names:
            img_path = image_paths.get(cam)
            
            if img_path is not None and img_path.exists():
                try:
                    img = Image.open(img_path).convert("RGB")
                    img = img.resize((self.image_size, self.image_size))
                    img_tensor = torch.from_numpy(
                        np.array(img).transpose(2, 0, 1)
                    ).float() / 255.0
                    images_by_cam[cam] = img_tensor
                    valid_by_cam[cam] = True
                except Exception as e:
                    print(f"Failed to load {img_path}: {e}")
                    images_by_cam[cam] = None
                    valid_by_cam[cam] = False
            else:
                images_by_cam[cam] = None
                valid_by_cam[cam] = False
        
        return {
            "images_by_cam": images_by_cam,
            "image_valid_by_cam": valid_by_cam,
            "episode_id": episode_id,
            "frame_idx": frame_idx,
        }


def multi_camera_simclr_loss(
    embeddings: Dict[str, torch.Tensor],
    valid_mask: Dict[str, torch.Tensor],
    temperature: float = 0.1,
) -> Optional[torch.Tensor]:
    """Multi-camera SimCLR-style contrastive loss.
    
    For each camera view, positives are OTHER cameras from the SAME frame.
    Negatives are all other frames (different spatial locations).
    
    Structure:
        batch_size = B, num_cams = C
        embeddings = [cam0_B, cam1_B, ... camC_B] -> (C*B, D)
        
    For sample at position i (representing camera c, frame b):
    - Positive: positions representing other cameras (c' != c) at same frame b
    - Negative: all cameras at different frames
    """
    valid_cams = [cam for cam, v in valid_mask.items() if v.any() and embeddings.get(cam) is not None]
    
    if len(valid_cams) < 2:
        return None
    
    # Stack embeddings: (num_cams, batch_size, D)
    embeddings_list = [embeddings[cam] for cam in valid_cams]
    features = torch.stack(embeddings_list, dim=0)
    num_cams, batch_size, dim = features.shape
    
    # Normalize
    features = F.normalize(features, dim=-1)
    
    # Reshape to (num_cams * batch_size, D)
    features_flat = features.transpose(0, 1).reshape(batch_size * num_cams, dim)
    
    # Compute similarity matrix
    sim = torch.matmul(features_flat, features_flat.T) / temperature
    sim = sim.float()  # Ensure float for numerical stability
    
    # Create positive mask: same frame (batch index), different camera
    # Position i corresponds to (camera_idx = i % num_cams, batch_idx = i // num_cams)
    # Positive if: batch_idx same AND camera_idx different
    pos_mask = torch.zeros_like(sim, dtype=torch.bool)
    
    for i in range(batch_size * num_cams):
        cam_i = i % num_cams
        batch_i = i // num_cams
        
        for j in range(batch_size * num_cams):
            cam_j = j % num_cams
            batch_j = j // num_cams
            
            # Positive if same batch, different camera
            if batch_i == batch_j and cam_i != cam_j:
                pos_mask[i, j] = True
    
    # Negative mask: exclude diagonal (self) and positives
    # SimCLR treats everything else as negative
    diagonal_mask = torch.eye(batch_size * num_cams, device=sim.device, dtype=torch.bool)
    neg_mask = ~(pos_mask | diagonal_mask)
    
    # For each sample, create a row with:
    # - positives at positive positions (for computing positive term)
    # - negatives at negative positions
    
    # Compute loss: -log(exp(pos) / (exp(pos) + exp(neg)))
    # = -pos + log(exp(pos) + exp(neg))
    # = -pos + logsumexp(sim[mask])
    
    # Use a numerically stable approach
    # For each row, compute: -sim[pos].mean() + log(sum(exp(sim[neg])))
    
    total_loss = 0.0
    valid_count = 0
    
    for i in range(batch_size * num_cams):
        pos_indices = pos_mask[i].nonzero(as_tuple=True)[0]
        neg_indices = neg_mask[i].nonzero(as_tuple=True)[0]
        
        if len(pos_indices) == 0 or len(neg_indices) == 0:
            continue
        
        # Positive term: -sim[i, pos].mean()
        pos_sim = sim[i, pos_indices].mean()
        
        # Negative term: logsumexp over negatives
        neg_sim = sim[i, neg_indices]
        neg_logsumexp = torch.logsumexp(neg_sim, dim=0)
        
        loss_i = -pos_sim + neg_logsumexp
        total_loss += loss_i
        valid_count += 1
    
    if valid_count == 0:
        return None
    
    loss = total_loss / valid_count
    
    if not torch.isfinite(loss):
        return None
    
    return loss


class TinyMultiCamEncoder(nn.Module):
    """Multi-camera encoder for contrastive SSL."""
    
    def __init__(
        self,
        camera_names: List[str] = None,
        embed_dim: int = 128,
    ):
        super().__init__()
        self.camera_names = camera_names or ["front", "left", "right", "rear"]
        self.embed_dim = embed_dim
        
        self.camera_encoders = nn.ModuleDict()
        for cam in self.camera_names:
            self.camera_encoders[cam] = nn.Sequential(
                nn.Conv2d(3, 32, 3, stride=2, padding=1),
                nn.ReLU(),
                nn.Conv2d(32, 64, 3, stride=2, padding=1),
                nn.ReLU(),
                nn.Conv2d(64, 128, 3, stride=2, padding=1),
                nn.ReLU(),
                nn.AdaptiveAvgPool2d((4, 4)),
                nn.Flatten(),
                nn.Linear(128 * 16, embed_dim),
            )
        
        self.fusion = nn.Linear(len(self.camera_names) * embed_dim, embed_dim)
    
    def per_cam(self, images: torch.Tensor) -> torch.Tensor:
        return self.camera_encoders[self.camera_names[0]](images)
    
    def forward(self, images_by_cam: Dict[str, torch.Tensor]) -> torch.Tensor:
        cam_embeddings = []
        
        for cam in self.camera_names:
            if cam not in images_by_cam:
                continue
            
            img = images_by_cam[cam]
            if img is None:
                continue
            
            emb = self.camera_encoders[cam](img)
            cam_embeddings.append(emb)
        
        if not cam_embeddings:
            return torch.zeros(1, self.embed_dim)
        
        if len(cam_embeddings) == 1:
            return cam_embeddings[0]
        
        concat = torch.cat(cam_embeddings, dim=-1)
        return self.fusion(concat)


def main():
    torch = _require_torch()
    
    parser = argparse.ArgumentParser(
        description="Contrastive SSL with Synthetic Waymo Episodes"
    )
    parser.add_argument("--episodes-dir", type=str, default=None)
    parser.add_argument("--images-dir", type=str, default=None)
    parser.add_argument("--batch-size", type=int, default=None)
    parser.add_argument("--num-steps", type=int, default=None)
    parser.add_argument("--lr", type=float, default=None)
    parser.add_argument("--out-dir", type=str, default=None)
    parser.add_argument("--temperature", type=float, default=None)
    parser.add_argument("--checkpoint-every", type=int, default=None)
    parser.add_argument("--log-every", type=int, default=None)
    args = parser.parse_args()
    
    cfg = Config()
    if args.episodes_dir is not None:
        cfg.episodes_dir = args.episodes_dir
    if args.images_dir is not None:
        cfg.images_dir = args.images_dir
    if args.batch_size is not None:
        cfg.batch_size = args.batch_size
    if args.num_steps is not None:
        cfg.num_steps = args.num_steps
    if args.lr is not None:
        cfg.lr = args.lr
    if args.out_dir is not None:
        cfg.out_dir = args.out_dir
    if args.temperature is not None:
        cfg.temperature = args.temperature
    if args.checkpoint_every is not None:
        cfg.checkpoint_every = args.checkpoint_every
    if args.log_every is not None:
        cfg.log_every = args.log_every
    
    print(f"[contrastive_ssl_synthetic] Config:")
    print(f"  episodes_dir: {cfg.episodes_dir}")
    print(f"  images_dir: {cfg.images_dir}")
    print(f"  batch_size: {cfg.batch_size}")
    print(f"  num_steps: {cfg.num_steps}")
    print(f"  temperature: {cfg.temperature}")
    
    os.makedirs(cfg.out_dir, exist_ok=True)
    
    config_path = os.path.join(cfg.out_dir, "config.json")
    with open(config_path, "w") as f:
        json.dump(cfg.__dict__, f, indent=2)
    print(f"Wrote config to {config_path}")
    
    print(f"Loading episodes from {cfg.episodes_dir}...")
    try:
        dataset = SyntheticEpisodesDataset(
            episodes_dir=cfg.episodes_dir,
            images_dir=cfg.images_dir,
            camera_names=["front", "left", "right", "rear"],
            image_size=cfg.image_size,
        )
        print(f"Loaded {len(dataset)} frames")
    except Exception as e:
        print(f"ERROR: Failed to load episodes: {e}")
        return
    
    encoder = TinyMultiCamEncoder(
        camera_names=["front", "left", "right", "rear"],
        embed_dim=cfg.encoder_out_dim,
    )
    encoder.train()
    
    optimizer = optim.Adam(encoder.parameters(), lr=cfg.lr)
    
    step = 0
    idx = 0
    train_start_time = time.time()
    training_metrics = {"steps": [], "loss": [], "lr": []}
    
    print(f"Starting training for {cfg.num_steps} steps...")
    
    while step < cfg.num_steps:
        batch_images = {}
        batch_valid = {}
        
        for cam in ["front", "left", "right", "rear"]:
            cam_imgs = []
            cam_valid = []
            
            for _ in range(cfg.batch_size):
                sample = dataset[idx % len(dataset)]
                idx += 1
                
                img = sample["images_by_cam"].get(cam)
                valid = sample["image_valid_by_cam"].get(cam, False)
                
                if img is not None and valid:
                    cam_imgs.append(img)
                    cam_valid.append(True)
                else:
                    cam_imgs.append(torch.zeros(3, cfg.image_size, cfg.image_size))
                    cam_valid.append(False)
            
            if cam_imgs:
                batch_images[cam] = torch.stack(cam_imgs)
                batch_valid[cam] = torch.tensor(cam_valid, dtype=torch.bool)
        
        valid_cams = [cam for cam, v in batch_valid.items() if v.any()]
        
        if len(valid_cams) < 2:
            if step % cfg.log_every == 0:
                print(f"step={step} (insufficient valid cameras, skipping)")
            step += 1
            continue
        
        per_cam_embeddings = {}
        for cam, images in batch_images.items():
            per_cam_embeddings[cam] = encoder.camera_encoders[cam](images)
        
        loss = multi_camera_simclr_loss(
            per_cam_embeddings,
            batch_valid,
            temperature=cfg.temperature,
        )
        
        if loss is None:
            if step % cfg.log_every == 0:
                print(f"step={step} (loss failed, skipping)")
            step += 1
            continue
        
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()
        
        if step % cfg.log_every == 0:
            elapsed = time.time() - train_start_time
            loss_val = float(loss.detach())
            print(f"step={step}/{cfg.num_steps} "
                  f"loss={loss_val:.4f} "
                  f"cams={valid_cams} "
                  f"time={elapsed:.1f}s")
            
            training_metrics["steps"].append(step)
            training_metrics["loss"].append(loss_val)
            training_metrics["lr"].append(optimizer.param_groups[0]["lr"])
        
        if step > 0 and step % cfg.checkpoint_every == 0:
            checkpoint_path = os.path.join(cfg.out_dir, f"checkpoint_{step:06d}.pt")
            checkpoint = {
                "step": step,
                "encoder": encoder.state_dict(),
                "optimizer": optimizer.state_dict(),
                "config": cfg.__dict__,
            }
            torch.save(checkpoint, checkpoint_path)
            print(f"Wrote checkpoint: {checkpoint_path}")
        
        step += 1
    
    final_model_path = os.path.join(cfg.out_dir, "encoder_final.pt")
    final_checkpoint = {
        "encoder": encoder.state_dict(),
        "config": cfg.__dict__,
        "training_metrics": training_metrics,
    }
    torch.save(final_checkpoint, final_model_path)
    print(f"Wrote final model: {final_model_path}")
    
    metrics_path = os.path.join(cfg.out_dir, "metrics.json")
    metrics = {
        "run_id": f"contrastive_ssl_synthetic_{int(time.time())}",
        "domain": "contrastive_ssl",
        "config": cfg.__dict__,
        "training_metrics": training_metrics,
    }
    with open(metrics_path, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"Wrote metrics: {metrics_path}")
    
    total_time = time.time() - train_start_time
    print(f"\n=== Training Complete ===")
    print(f"Steps: {step}")
    print(f"Time: {total_time:.1f}s")
    print(f"Final loss: {training_metrics['loss'][-1] if training_metrics['loss'] else 'N/A'}")
    print(f"Output: {cfg.out_dir}")


if __name__ == "__main__":
    main()